@startuml
title Game utils
class game.game_state_util {
{static} calculate_starting_hands_from_game()
{static} calculate_points_from_tricks()
{static} observation_from_state()
{static} state_from_complete_game()
{static} state_for_trump_from_complete_game()
}

class game.game_util {
{static} get_cards_encoded()
{static} get_cards_encoded_from_str()
{static} convert_str_encoded_cards_to_int_encoded()
{static} convert_int_encoded_cards_to_str_encoded()
{static} convert_one_hot_encoded_cards_to_str_encoded_list()
{static} convert_one_hot_encoded_cards_to_int_encoded_list()
{static} count_colors()
{static} deal_random_hand()
}
@enduml